INSERT INTO book (id, title, author) VALUES (nextval('book_seq'), 'Testy', 'Kaczanowski');
INSERT INTO book (id, title, author) VALUES (nextval('book_seq'), 'Dzuma','Camus');
INSERT INTO book (id, title, author) VALUES (nextval('book_seq'), 'W pustyni i w puszczy', 'Sienkiewicz');
INSERT INTO book (id, title, author) VALUES (nextval('book_seq'), 'Pan Tadeusz', 'Mickiewicz');
INSERT INTO book (id, title, author) VALUES (nextval('book_seq'), 'Dziady', 'Mickiewicz');
INSERT INTO book (id, title, author) VALUES (nextval('book_seq'), 'Anioly i demony', 'Brown');
INSERT INTO book (id, title, author) VALUES (nextval('book_seq'), 'Gra o tron', 'Martin');
INSERT INTO book (id, title, author) VALUES (nextval('book_seq'), 'Harry Potter', 'Rowling');
INSERT INTO book (id, title, author) VALUES (nextval('book_seq'), 'Testy', 'Kaczanowski');
INSERT INTO book (id, title, author) VALUES (nextval('book_seq'), 'Testy', 'Kaczanowski');
commit;